### ISSUE TITLE
图片存不了，什么qiniu status code: -1

### ISSUE THREAD

**Issue by EvergreenHZ** [leancloud/javascript-sdk#533]
``Traceback (most recent call last):
  File "leanCloudTest.py", line 21, in <module>
    todo.save()
  File "/usr/local/lib/python2.7/dist-packages/leancloud/object_.py", line 229, in save
    self._deep_save(unsaved_children, unsaved_files, exclude=self._attributes)
  File "/usr/local/lib/python2.7/dist-packages/leancloud/object_.py", line 249, in _deep_save
    f.save()
  File "/usr/local/lib/python2.7/dist-packages/leancloud/file_.py", line 250, in save
    self._save_to_qiniu(content['token'], content['key'])
  File "/usr/local/lib/python2.7/dist-packages/leancloud/file_.py", line 179, in _save_to_qiniu
    raise LeanCloudError(1, 'the file is not saved, qiniu status code: {0}'.format(info.status_code))
leancloud.errors.LeanCloudError: LeanCloudError: [1] the file is not saved, qiniu status code: -1

**Comment by leeyeh** [comment]
看起来是 python SDK 抛出的异常。
