### ISSUE TITLE
错误处理的bug

### ISSUE THREAD

**Issue by GongT** [leancloud/javascript-sdk#540]
这一行：https://github.com/leancloud/javascript-sdk/blob/master/src/request.js#L133

如果服务器返回了**非200**状态的**HTML**    
* `error.message = Http Status Text`
* `error.response = undefined` 

那么返回的HTML就被扔了，于是没法知道到底啥问题

例：

`AV.init({ production: false })`
请求 `requestSmsCode`

实际返回的是：
```html
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>\n<title>Error 500 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 500</h2>\n<p>Problem accessing /1.1/requestSmsCode. Reason:\n<pre>    For input string: "false"</pre></p>\n<hr /><i><small>Powered by Jetty://</small></i>\n</body>\n</html>\n
```

程序中只能捕获到这个：
```
RequestError: Internal Server Error [500 POST https://vlyl0hrw.api.lncld.net/1.1/requestSmsCode]
    at /data/DevelopmentRoot/work/admin-platform-server/node_modules/leancloud-storage/dist/node/request.js:165:17
    at tryCatch (/data/DevelopmentRoot/work/admin-platform-server/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:188:12)
```

**Comment by leeyeh** [comment]
```
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>\n<title>Error 500 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 500</h2>\n<p>Problem accessing /1.1/requestSmsCode. Reason:\n<pre>    For input string: "false"</pre></p>\n<hr /><i><small>Powered by Jetty://</small></i>\n</body>\n</html>\n
```

这个首先不对的是，我们的服务不应该返回这种 HTML 状态的异常，我调查一下。
