### ISSUE TITLE
AV.Cloud.run() 无法使用,调用失败

### ISSUE THREAD

**Issue by gwuhaolin** [leancloud/javascript-sdk#77]
当调用AV.Cloud.run()执行云函数时,采用的时POST方法到https://cn.avoscloud.com,导致跨域从而导致调用失败,如图是chrome记录的发包:
![screen shot 2015-04-08 at 21 10 15](https://cloud.githubusercontent.com/assets/5773264/7045784/b50e1a02-de33-11e4-9e66-7490137a24f5.png)
如下是我完整的代码:
```
                    AV.Cloud.run('saveWechatImageToUsedBook', {
                        serverId: wechatServerId,
                        objectId: avosUsedBook.objectId
                    }, null).done(function () {
                        alert('AVOS下载图片成功');
                    }).fail(function (error) {
                        alert(error.message);
                    })
```

用的js-sdk版本是  root.AV.VERSION = "js0.5.1";

**Comment by killme2008** [comment]
没有看到图，我测试没有问题：

![snip20150410_3](https://cloud.githubusercontent.com/assets/14142/7082446/ee2006bc-df86-11e4-8361-ef19bf8be883.png)

**Comment by killme2008** [comment]
400 请求是你的函数返回的错误，跟跨域无关，请自行跟踪调试。

**Comment by gwuhaolin** [comment]
![screen shot 2015-04-10 at 15 09 53](https://cloud.githubusercontent.com/assets/5773264/7083382/bf86f74a-df93-11e4-8342-d725dfa3e028.png)
这是在chrome里的网页调用云函数时控制台打印的错误日志

**Comment by killme2008** [comment]
返回400了，看下错误信息吧，这个问题跟跨域无关

**Comment by gwuhaolin** [comment]
我在本地调试了一下云代码,每次调用云代码nodejs控制台都打印如下:
```
TypeError: Cannot read property 'uid' of undefined
    at processRequest (/usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:464:23)
    at /usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:577:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/express/lib/router/index.js:400:3)
```
是因为我云函数写错的问题吗?

**Comment by gwuhaolin** [comment]
我查了很久没找到服务器返回400是代表什么,可以给一个关于400 的说明链接吗?
